### ISSUE TITLE
Not Compitable with Chrome extension MV3

### ISSUE THREAD

**Issue by nirvparekh** [InboxSDK/inboxsdk-docs#6]
Getting error in Gmail from content script.
`contentScript.bundle.js:54998 Error logged: EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at eval (<anonymous>)
    at contentScript.bundle.js:54820 

Original error stack:
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at eval (<anonymous>)
    at chrome-extension://ipjpliddiedabogjnnnkaojcfaiccbdm/contentScript.bundle.js:54820:27 

Error logged from:
    at logError (chrome-extension://ipjpliddiedabogjnnnkaojcfaiccbdm/contentScript.bundle.js:54976:56)
    at chrome-extension://ipjpliddiedabogjnnnkaojcfaiccbdm/contentScript.bundle.js:54861:38 

Error details: {url: 'https://www.inboxsdk.com/build/platform-implementation.js', connectivityTestResults: {…}, status: undefined, response: null, message: 'Failed to load script'}`

**Comment by Macil** [comment]
The InboxSDK doesn't support MV3 yet because of its current reliance on remote loading code. There's some information here about it: https://groups.google.com/g/inboxsdk/c/ho69zTWjxgM/m/PhrWenZcAQAJ. The InboxSDK will be MV3-compatible before it becomes required by Chrome.
